FROM node:12.13.0

# Create app directory in container
RUN mkdir -p /usr/src/api
WORKDIR /usr/src/api

# Install app dependencies
COPY package.json /usr/src/api
RUN npm install

# Bundle app source
COPY . /usr/src/api

# Build arguments
ARG NODE_VERSION=12.13.0

# Environment
ENV NODE_VERSION $NODE_VERSION